# Blog meta-information
blog:
  title:  "kLog"       # Displayed as <title> on index page
  name:   "kLog"  # Displayed as part of <title> on article page
  author: "Kelly McLaughlin"                # Used in feeds
  email:  "mclaughlin77@gmail.com"              # Used in feeds

# Admin credentials (prepend article URL with URL to see why)
admin:
  username: 'admin'
  password: 'sup3rm2n   '

# Set this relatively to application main ("marley") directory
data_directory: "./data"

# Set this to your own theme in "themes" directory
theme: "kelly-mclaughlin"

# Google Analytics code ("UA-123132-00" etc)
ga_code: ~

# If you want to add synchronizing via Github post-receive hooks, insert some secure password here
# Then set a "Post-Receive URL" in Github administration to http://{YOUR SERVER}/sync?token={WHAT YOU SET BELOW}
github_token: ~

# See http://soakedandsoaped.com/articles/2006/10/01/how-to-protect-a-rails-application-against-spam-with-akismet
akismet: 
  key: "ee69248a5c0a"
  url: "www.kelly-mclaughlin.com"
